### ISSUE TITLE
FIX API

### ISSUE THREAD

**Issue by jvirtanen** [jvirtanen/parity#15]
Market participants should be able to enter orders using the [FIX](http://www.fixtradingcommunity.org) protocol.

**Comment by divaykin** [comment]
Something basic / slow would be sufficient. Even QuickFIX/J FIX 4.2 would be okay

**Comment by penberg** [comment]
QuickFIX/J APIs are not that much fun to work with. Perhaps we can start with something simpler :wink: 

https://github.com/penberg/falcon

**Comment by divaykin** [comment]
falcon do not support message parsing / listening isn't it?

**Comment by divaykin** [comment]
actually it does a bit i.e. there is a recv method, I guess we could plug it into Netty?

**Comment by penberg** [comment]
@divaykin Yes, we certainly could plug it into Netty.

**Comment by divaykin** [comment]
@penberg @jvirtanen you guys have some motivation to get the tool to production usage? some efforts would be needed...

**Comment by jvirtanen** [comment]
Yes, [Falcon](https://github.com/penberg/falcon) would indeed need some work before it would be usable. Also, I don't see QuickFIX/J as a viable solution in the long term.

In the big picture, a FIX interface becomes important when we start introduce more variation in order types, matching algorithms, and other parameters. Based on what I've been able to decipher, [Cinnober](http://www.cinnober.com) and [MillenniumIT](http://www.millenniumit.com) appear to offer exclusively a FIX interface for order entry on their trading systems.

**Comment by divaykin** [comment]
@jvirtanen there are lot of exchanges (I'd say like 60-70% in terms of numbers and 80% in terms of global volume) what do exclusively FIX.

**Comment by jvirtanen** [comment]
I have been working on a brand new FIX engine for the JVM during the past few weeks. It looks quite promising: there are no memory allocations at all on message reception or transmission. All field types can also be read and written without causing any memory allocations. I hope to release the initial version soon.

**Comment by sirinath** [comment]
Looking forward to this. What about other protocols?

**Comment by jvirtanen** [comment]
@sirinath Do you have some specific protocols in mind?

**Comment by sirinath** [comment]
I don't have any in mind but it would be good to have many of the native protocols for order flow and feeds.

Having said this FAST, encoding FIX using GBP, SBE will be desired through the latter may not have much of a following as yet.

**Comment by jvirtanen** [comment]
@sirinath Yes, I think that it might become useful to pair FIX on the order entry with, say, SBE for market data as we start supporting multiple matching algorithms or market mechanics (#44). The binary protocols begin to lose their edge as soon as variation is introduced.

**Comment by jvirtanen** [comment]
The aforementioned brand new FIX engine, [Philadelphia](https://github.com/jvirtanen/philadelphia), is now available as an open source project.

**Comment by jvirtanen** [comment]
See #56.
