### ISSUE TITLE
Recorded market data replay

### ISSUE THREAD

**Issue by divaykin** [jvirtanen/parity#43]
Would be great to be able to replay recorded market data with particular speedup factor i.e. X1 - realtime, X5 - time time faster vs realtime, etc.

Market data should interact with user orders in a correct way. The tricky part is - for example replayed order for 200shs was executed against user order partially and 100shs remaining. Then market data can show that this order was increased to 300shs but in reality we may want to assume that order would have a size of 200shs (100shs consumed by user).

**Comment by divaykin** [comment]
I would not do this through normal order entry interface because streaming all this through network stack would make the process relatively slow

**Comment by penberg** [comment]
IIRC, @jvirtanen mentioned privately few weeks back that he's working on something like that for NASDAQ ITCH 5.0 using Juncture:

https://github.com/jvirtanen/juncture

**Comment by jvirtanen** [comment]
Yes, I'm working on this for NASDAQ TotalView-ITCH 5.0. It is a separate application that interfaces with the matching engine using the market data and order entry protocols.

In the future the trading system will be split into multiple applications: order entry gateways, matching engines, and market data gateways. While this is necessary for reliability and scalability, it is also helpful for applications such as this. The interfaces within the trading system could be based on [Aeron](https://github.com/real-logic/Aeron), for example.

**Comment by jvirtanen** [comment]
This issue is moved to [#2](https://github.com/jvirtanen/parity-extras/issues/2) on [Parity Extras](https://github.com/jvirtanen/parity-extras).
