### ISSUE TITLE
Strip to Lib and publish on maven

### ISSUE THREAD

**Issue by sirinath** [jvirtanen/parity#47]
Parity related projects will be more useful if you strip the components into libraries and publish on maven.

**Comment by jvirtanen** [comment]
Parity actually consists of a set of applications and libraries, both of which are [available on Maven](http://search.maven.org/#search%7Cga%7C1%7Cparity). [NASDAQ Market Data Tools](https://github.com/jvirtanen/nasdaq-tools) is an example of an external project utilizing them. It uses [Parity File Formats](https://github.com/jvirtanen/parity/tree/master/parity-file) and [Parity Top of Book](https://github.com/jvirtanen/parity/tree/master/parity-top).

**Comment by sirinath** [comment]
I think you need some documentation somewhere.

**Comment by jvirtanen** [comment]
True, the documentation is quite thin at the moment. I will try to find time to make some improvements on it.

**Comment by sirinath** [comment]
May you you can do a skeleton 1st and fill in the flesh when you find more time. The skeleton which just show the component is just there.
